FROM python:3.11-alpine
RUN mkdir flask_task
WORKDIR  /flask_task
COPY ./pyproject.toml ./
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install
COPY . .
CMD ["python3", "app.py"]
